spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql03
    username: root
    password: root

mybatis:
  mapper-locations: classpath:com/jpl/mapper/*.xml
  type-aliases-package: com.jpl.pojo